# Generated by Django 2.1.1 on 2018-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180929_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='property',
            field=models.ForeignKey(on_delete='CASCADE', related_name='images', to='projects.Project'),
        ),
    ]
