# Generated by Django 2.1.1 on 2018-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180929_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='property',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete='CASCADE', related_name='images', to='projects.Project'),
        ),
    ]
