# Generated by Django 2.1.1 on 2018-09-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactdetail_image_700x458_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetail',
        ),
    ]
